[package]
name = "discord_term"
version = "0.1.0"
authors = ["Em Sal <absolutezero2a03@gmail.com>"]

[dependencies]
tui="0.2.1"
termion="1.5.1"
discord= { git = "https://github.com/tinaun/discord-rs", branch="master"}
chan="0.1.21"
rpassword = "0.0.4"
