[package]
name = "discord_term"
version = "0.1.0"
authors = ["Em Sal <absolutezero2a03@gmail.com>"]

[dependencies]
tui="0.2.0"
termion="1.4.0"
discord= { git = "https://github.com/jimqi/discord-rs.git", branch="master"}
chan="0.1.19"
rpassword = "0.0.4"